ETrade.UI/Models/ErrorViewModel.cs
namespace ETrade.UI.Models
{
    public class ErrorViewModel
    {
        public string? RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

ETrade.UI/Models/ViewModel/AdminModel.cs
﻿using ETrade.Ent;

namespace ETrade.UI.Models.ViewModel
{
    public class AdminModel
    {
        public AdminModel()
        {
            SelectedFood = new Foods();
        }
        public Foods SelectedFood { get; set; }
        public List<Categories> Categories { get; set; }
        public List<Properties> Properties { get; set; }
        public string Head { get; set; }
        public string Text { get; set; }
        public string Class { get; set; }
    }
}

ETrade.UI/Models/ViewModel/BaseCrud.cs
using ETrade.Ent;

namespace ETrade.UI.Models.ViewModel
{
    public class BaseCrud
    {
        public string Head { get; set; }
        public string Text { get; set; }
        public string Class { get; set; }

    }
}

ETrade.UI/Models/ViewModel/CategoriesModel.cs
using ETrade.Ent;

namespace ETrade.UI.Models.ViewModel
{
    public class CategoriesModel : BaseCrud
    {
        public Categories Categories { get; set; } = new Categories();
        public decimal Price { get; set; }
    }
}

ETrade.UI/Models/ViewModel/FoodsModel.cs
using ETrade.DTO;
using ETrade.Ent;

namespace ETrade.UI.Models.ViewModel
{
    public class FoodsModel : BaseCrud
    {
        public Foods Foods { get; set; } = new Foods();

        public List<CategoriesDTO> Cats { get; set; }
    }
}

ETrade.UI/Models/ViewModel/PropertiesModel.cs
using ETrade.DTO;
using ETrade.Ent;

namespace ETrade.UI.Models.ViewModel
{
    public class PropertiesModel : BaseCrud
    {
        public Properties Properties { get; set; } = new Properties();
        // we need select-option prop so we use foodDTO
        public List<FoodDTO> FoodDTOs { get; set; }
    }
}

ETrade.UI/Controllers/AdminController.cs
using ETrade.UI.Models.ViewModel;
using ETrade.UoW;
using Microsoft.AspNetCore.Mvc;

namespace ETrade.UI.Controllers
{
    public class AdminController : BaseController
    {
        private readonly BaseCrud model;

        public AdminController(IUoW uow, BaseCrud model) : base(uow)
        {
            this.model = model;
        }

        public IActionResult Admin()
        {
            return View();
        }

        //public IActionResult List()
        //{
        //	//return View(Uow.foodRepos.GetFoods());
        //}


    }
}

ETrade.UI/Controllers/AuthController.cs
using Microsoft.AspNetCore.Mvc;

namespace ETrade.UI.Controllers
{
    public class AuthController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }
    }
}

ETrade.UI/Controllers/BaseController.cs
using ETrade.UoW;

using Microsoft.AspNetCore.Mvc;

namespace ETrade.UI.Controllers
{
    public class BaseController : Controller
    {
        public IUoW Uow;

        public BaseController(IUoW uow)
        {
            Uow = uow;
        }
    }
}

ETrade.UI/Controllers/CategoriesController.cs
using ETrade.UI.Models.ViewModel;
using ETrade.UoW;
using Microsoft.AspNetCore.Mvc;

namespace ETrade.UI.Controllers
{
    public class CategoriesController : BaseController
    {

        private readonly CategoriesModel model;

        public CategoriesController(IUoW uow, CategoriesModel model) : base(uow)
        {

            this.model = model;
        }

        public IActionResult List()
        {
            return View(Uow.catRepos.GetCategories());
        }
        public IActionResult Create()
        {
            model.Text = "Save";
            model.Head = "New Categories";
            model.Class = "btn btn-outline-success my-2";

            return View("Crud", model);
        }
        [HttpPost]
        public IActionResult Create(CategoriesModel model)
        {

            Uow.catRepos.Add(model.Categories);
            Uow.Commit();
            return RedirectToAction("List");
        }
        public IActionResult Update(Guid Id)
        {
            model.Text = "Save";
            model.Head = "Update Categories";
            model.Class = "btn btn-outline-success my-2";
            model.Categories = Uow.catRepos.Find(Id);

            return View("Crud", model);
        }
        [HttpPost]
        public IActionResult Update(CategoriesModel model)
        {

            Uow.catRepos.Update(model.Categories);
            Uow.Commit();
            return RedirectToAction("List");
        }
        public IActionResult Delete(Guid Id)
        {

            Uow.catRepos.Delete(Uow.catRepos.Find(Id));
            Uow.Commit();
            return RedirectToAction("List");
        }

    }
}

ETrade.UI/Controllers/FoodController.cs
using ETrade.DTO;
using ETrade.UI.Models.ViewModel;
using ETrade.UoW;

using Microsoft.AspNetCore.Mvc;

namespace ETrade.UI.Controllers
{
    public class FoodController : BaseController
    {
        private readonly FoodsModel model;


        public FoodController(IUoW uow, FoodsModel model) : base(uow)
        {
            this.model = model;
        }


        public IActionResult List()
        {
            return View(Uow.foodRepos.GetFoods());
        }
        public IActionResult Create()
        {
            model.Text = "Save";
            model.Head = "New Foods";
            model.Class = "btn btn-outline-success my-2";
            model.Cats = Uow.catRepos.GetCategories();
            return View("Crud", model);
        }
        [HttpPost]
        public IActionResult Create(FoodsModel model)
        {

            Uow.foodRepos.Add(model.Foods);
            Uow.Commit();
            return RedirectToAction("List");
        }
        public IActionResult Update(Guid Id)
        {
            model.Text = "Save";
            model.Head = "Update Properties";
            model.Class = "btn btn-outline-success my-2";
            model.Foods = Uow.foodRepos.Find(Id);
            model.Cats = Uow.catRepos.GetCategories();

            return View("Crud", model);
        }
        [HttpPost]
        public IActionResult Update(FoodsModel model)
        {

            Uow.foodRepos.Update(model.Foods);
            Uow.Commit();
            return RedirectToAction("List");
        }
        public IActionResult Delete(Guid Id)
        {
            Uow.foodRepos.Delete(Uow.foodRepos.Find(Id));
            Uow.Commit();
            return RedirectToAction("List");
        }
    }
}

ETrade.UI/Controllers/HomeController.cs
using ETrade.UI.Models;
using Microsoft.AspNetCore.Mvc;
using System.Diagnostics;

namespace ETrade.UI.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

ETrade.UI/Controllers/OrdersController.cs
using ETrade.UoW;
using Microsoft.AspNetCore.Mvc;

namespace ETrade.UI.Controllers
{
    public class OrdersController : BaseController
    {
        public OrdersController(IUoW uow) : base(uow)
        {
        }

        public IActionResult List()
        {
            return View(uow.OrderRepository.List());
        }
    }
}

ETrade.UI/Views/Admin/Admin.cshtml
@{
    ViewData["Title"] = "Admin";
    Layout = "~/Views/Shared/_LayoutAdmin.cshtml";
}

<h1>Admin</h1>

ETrade.UI/Views/Categories/Crud.cshtml
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@model ETrade.UI.Models.ViewModel.CategoriesModel
@{    ViewData["Title"] = "Create";
    Layout = "~/Views/Shared/_LayoutAdmin.cshtml";
}

<h1>@Model.Head</h1>


<hr />
<div class="row">
    <div class="col-md-4">
        <form method="post">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="Categories.CategoryId" />
            <div class="form-group">
                <label asp-for="Categories.CategoryId" class="control-label"><h4>Category Name</h4></label>
                <input asp-for="Categories.CategoryName" class="form-control" />
                <span asp-validation-for="Categories.CategoryName" class="text-danger"></span>
            </div>
            @*<div class="form-group">
                <input type="hidden" name="@Model.Categories.Id" class="form-control" />
            </div>*@
            <div class="form-group">
                <input type="submit" value="@Model.Text" class="@Model.Class" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="List" class="btn btn-outline-warning">Back to List</a>
</div>

@section Scripts {
    @{
        await Html.RenderPartialAsync("_ValidationScriptsPartial");
    }
}

ETrade.UI/Views/Categories/List.cshtml
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@model IEnumerable<ETrade.DTO.CategoriesDTO>
@{
    ViewData["Title"] = "List";
    Layout = "~/Views/Shared/_LayoutAdmin.cshtml";
}

<h1>List</h1>

<p>
    <a asp-action="Create">Create New Categories</a>
</p>
<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.Id)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.CategoryName)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
        @foreach (var item in Model)
        {
            <tr>
                <td>
                    @Html.DisplayFor(modelItem => item.Id)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.CategoryName)
                </td>
                <td>
                    @Html.ActionLink("Update", "Update", new { id=item.Id }) |
                    @Html.ActionLink("Details", "Details", new { id = item.Id }) |
                    @Html.ActionLink("Delete", "Delete", new { id = item.Id })
                </td>
            </tr>
        }
    </tbody>
</table>

ETrade.UI/Views/Food/Crud.cshtml
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@model ETrade.UI.Models.ViewModel.FoodsModel
@{
	ViewData["Title"] = "Create";
	Layout = "~/Views/Shared/_LayoutAdmin.cshtml";
}





<h1>@Model.Head</h1>


<hr />
<div class="row">
	<div class="col-md-4">
		<form method="post">
			<div asp-validation-summary="ModelOnly" class="text-danger"></div>
			<input type="hidden" asp-for="Foods.FoodId" />
			<div class="form-group">
				<label>Food Name</label>
				<input asp-for="Foods.FoodName" class="form-control" />
			</div>
			<div class="form-group">
				<label>Desc</label>
				<input asp-for="Foods.Description" class="form-control" />
			</div>
			<div class="form-group">
				<label>Img</label>
				<input asp-for="Foods.Img" class="form-control" />
			</div>
			<div class="form-group">
				<label>Categories</label>
				<select name="Foods.CategoryId">
					@*@foreach (var item in Model.Cats)
					{
					<option selected value="@item.Id" class="form-control">@item.CategoryName</option>
					}*@
					@foreach (var item in Model.Cats)
					{
						@if (item.Id == Model.Foods.CategoryId)
						{
							<option selected value="@item.Id" class="form-control">@item.CategoryName</option>
						}
						else
						{
							<option value="@item.Id" class="form-control">@item.CategoryName</option>
						}

					}
					
				</select>
			</div>
			
			@*<div class="form-group">
			<input type="hidden" name="@Model.Foods.FoodId" class="form-control" />
			</div>*@
			<div class="form-group">
				<input type="submit" value="@Model.Text" class="@Model.Class" />
			</div>
		</form>
	</div>
</div>

<div>
	<a asp-action="List" class="btn btn-outline-warning">Back to List</a>
</div>

@section Scripts {
	@{
		await Html.RenderPartialAsync("_ValidationScriptsPartial");
	}
}

ETrade.UI/Views/Food/List.cshtml
@model IEnumerable<ETrade.DTO.FoodDTO>

@{
    ViewData["Title"] = "List";
    Layout = "~/Views/Shared/_LayoutAdmin.cshtml";
}

<h1>List</h1>

<p>
    <a asp-action="Create">Create New Food</a>
</p>
<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.Id)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.FoodName)
            </th>
            
            <th></th>
        </tr>
    </thead>
    <tbody>
        @foreach (var item in Model)
        {
            <tr>
                <td>
                    @Html.DisplayFor(modelItem => item.Id)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.FoodName)
                </td>
                
                <td>
                    @Html.ActionLink("Update", "Update", new { id=item.Id }) |
                    @Html.ActionLink("Details", "Details", new { id = item.Id }) |
                    @Html.ActionLink("Delete", "Delete", new { id = item.Id })
                </td>
            </tr>
        }
    </tbody>
</table>

ETrade.UI/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">Welcome</h1>
    <p>Learn about <a href="https://docs.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>
</div>

ETrade.UI/Views/Orders/List.cshtml
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
}
@model List<ETrade.Ent.Orders>
@{
    ViewData["Title"] = "List";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<div class="bg-white shadow rounded-lg p-4 sm:p-6 xl:p-8 ">
    <div class="mb-4 flex items-center justify-between">
        <div>
            <h3 class="text-xl font-bold text-gray-900 mb-2">Orders</h3>
            <span class="text-base font-normal text-gray-500">This is a list of orders</span>
        </div>
        <div class="flex-shrink-0">
            <a asp-action="Create" class="text-sm font-medium text-cyan-600 hover:bg-gray-100 rounded-lg p-2">New Orders</a>
        </div>
    </div>
    <div class="flex flex-col mt-8">
        <div class="overflow-x-auto rounded-lg">
            <div class="align-middle inline-block min-w-full">
                <div class="shadow overflow-hidden sm:rounded-lg">
                    <table class="min-w-full divide-y divide-gray-200">
                        <thead class="bg-gray-50">
                            <tr>
                                <th scope="col" class="p-4 text-left text-xs font-medium text-gray-500 uppercase tracking-wider">
                                    ID
                                </th>
                                <th scope="col" class="p-4 text-left text-xs font-medium text-gray-500 uppercase tracking-wider">
                                    OrderDate
                                </th>
                                <th scope="col" class="p-4 text-left text-xs font-medium text-gray-500 uppercase tracking-wider">
                                    Shipping Address
                                </th>
                            </tr>
                        </thead>
                        <tbody class="bg-white">
                            @foreach (var item in Model)
                            {
                                <tr>
                                    <td class="p-4 whitespace-nowrap text-sm font-normal text-gray-900">
                                        @item.OrderId
                                    </td>
                                    <td class="p-4 whitespace-nowrap text-sm font-normal text-gray-500">
                                        @item.CreatedAt
                                    </td>
                                    <td class="p-4 whitespace-nowrap text-sm font-semibold text-gray-900">
                                        @item.ShippingAddress
                                    </td>
                                </tr>
                            }
                        </tbody>
                    </table>
                </div>
            </div>
        </div>
    </div>
</div>

ETrade.UI/Views/Properties/Crud.cshtml
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@model ETrade.UI.Models.ViewModel.PropertiesModel
@{
    ViewData["Title"] = "Create";
    Layout = "~/Views/Shared/_LayoutAdmin.cshtml";
}﻿

<h1>@Model.Head</h1>


<hr />
<div class="row">
    <div class="col-md-4">
        <form method="post">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="Properties.PropertyId" />
            <div class="form-group">
                <label>Ad</label>
                <input asp-for="Properties.PropertyName" class="form-control" />
                
            </div>
            @*<div class="form-group">
            <input type="hidden" name="@Model.Categories.Id" class="form-control" />
            </div>*@
            @*PRICE*@
            <div class="form-group">
                <label>Unit Price</label>
                <input asp-for="Properties.UnitPrice" class="form-control" />
                
            </div>

            <div class="form-group">
                <label>Foods</label>
                <select>
                    @foreach (var item in Model.FoodDTOs)
                    {
                        <option selected value="@item.Id" class="form-control">@item.FoodName</option>
                    }
                </select>
            </div>
            @*<div class="form-group">
            <input type="hidden" name="@Model.Properties.PropertyId" class="form-control" />
            </div>*@
            <div class="form-group">
                <input type="submit" value="@Model.Text" class="@Model.Class" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="List" class="btn btn-outline-warning">Back to List</a>
</div>

@section Scripts {
    @{
        await Html.RenderPartialAsync("_ValidationScriptsPartial");
    }
}

ETrade.UI/Views/Properties/List.cshtml
@model IEnumerable<ETrade.DTO.PropertiesDTO>

@{
    ViewData["Title"] = "List";
    Layout = "~/Views/Shared/_LayoutAdmin.cshtml";
}

<h1>List</h1>

<p>
    <a asp-action="Create">Create New Properties</a>
</p>
<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.Id)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.PropertyName)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
        @foreach (var item in Model)
        {
            <tr>
                <td>
                    @Html.DisplayFor(modelItem => item.Id)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.PropertyName)
                </td>
                <td>
                    @Html.ActionLink("Update", "Update", new { id=item.Id }) |
                    @Html.ActionLink("Details", "Details", new { id = item.Id }) |
                    @Html.ActionLink("Delete", "Delete", new { id = item.Id })
                </td>
            </tr>
        }
    </tbody>
</table>

ETrade.UI/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - ETrade.UI</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/ETrade.UI.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">ETrade.UI</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Admin" asp-action="Admin">Admin</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2023 - ETrade.UI - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

ETrade.UI/Views/Shared/_LayoutAdmin.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
	<meta charset="utf-8" />
	<meta name="viewport" content="width=device-width, initial-scale=1.0" />
	<title>@ViewData["Title"] - ETrade.UI</title>
	<link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
	<link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
	<link rel="stylesheet" href="~/ETrade.UI.styles.css" asp-append-version="true" />
</head>
<body>
	<header>
		<nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
			<div class="container-fluid">
				<a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">ETrade.UI</a>
				<button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
						aria-expanded="false" aria-label="Toggle navigation">
					<span class="navbar-toggler-icon"></span>
				</button>
				<div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
					<ul class="navbar-nav flex-grow-1">
						<li class="nav-item">
							<a class="nav-link text-dark" asp-area="" asp-controller="Food" asp-action="List">Foods</a>
						</li>
						<li class="nav-item">
							<a class="nav-link text-dark" asp-area="" asp-controller="Properties" asp-action="List">Properties</a>
						</li>
						<li class="nav-item">
							<a class="nav-link text-dark" asp-area="" asp-controller="Categories" asp-action="List">Categories</a>
						</li>

					</ul>
				</div>
			</div>
		</nav>
	</header>
	<div class="container">
		<main role="main" class="pb-3">
			@RenderBody()
		</main>
	</div>

	<footer class="border-top footer text-muted">
		<div class="container">
			&copy; 2023 - ETrade.UI - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
		</div>
	</footer>
	<script src="~/lib/jquery/dist/jquery.min.js"></script>
	<script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
	<script src="~/js/site.js" asp-append-version="true"></script>
	@await RenderSectionAsync("Scripts", required: false)
</body>
</html>